endpoint: https://ucblib.atlassian.net
user: matienzo@berkeley.edu
password-source: keyring
custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "" ]; then
          # if  configured just list the issues for current project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() and project =  ORDER BY priority asc, created"
      else
          # otherwise list issues for all project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi
